export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS"
export const FETCH_LOCATION_ERROR = "FETCH_LOCATION_ERROR"

export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS"
export const FETCH_WEATHER_ERROR = "FETCH_WEATHER_ERROR"

export const CURRENT_SUCCESS = "CURRENT_SUCCESS"
export const CURRENT_ERROR = "CURRENT_ERROR"
